name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            hernanisoares/conversaopeso:latest
            hernanisoares/conversaopeso:${{ github.run_number }}
          
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_K8S }}

      - uses: prepor/action-aws-iam-authenticator@master
      - run: aws-iam-authenticator version
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.5
        with:
          images: hernanisoares/conversaopeso:${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml
